alias sudo-reboot='sudo reboot'               # Reinicia el sistema inmediatamente.
alias sudo-poweroff='sudo poweroff'           # Apaga el sistema inmediatamente.
alias sudo-rmf='sudo rm -rf'                  # Elimina archivos o directorios de forma recursiva y forzada.
alias sudo-chmod='sudo chmod'                 # Cambia permisos en archivos o carpetas.
alias sudo-chown='sudo chown'                 # Cambia el propietario de archivos o carpetas.
alias sudo-mkdir='sudo mkdir'                 # Crea un nuevo directorio con privilegios de superusuario.
alias sudo-vim='sudo vim'                     # Abre archivos con Vim usando permisos de superusuario.
alias sudo-cp='sudo cp'                       # Copia archivos o carpetas con permisos de superusuario.
alias sudo-mv='sudo mv'                       # Mueve o renombra archivos o carpetas con permisos de superusuario.
alias sudo-ln='sudo ln -s'                    # Crea enlaces simbólicos con permisos de superusuario.
alias sudo-du='sudo du -h'                    # Muestra el uso de disco de forma recursiva con permisos.
alias sudo-df='sudo df -h'                    # Muestra el espacio en disco disponible con permisos.
alias sudo-lsof='sudo lsof'                   # Lista los archivos abiertos por procesos.
alias sudo-service-start='sudo systemctl start'  # Inicia un servicio en el sistema.
alias sudo-service-stop='sudo systemctl stop'    # Detiene un servicio en el sistema.
alias sudo-service-status='sudo systemctl status' # Verifica el estado de un servicio.
alias sudo-apt-install='sudo apt install'     # Instala paquetes con APT.
alias sudo-apt-remove='sudo apt remove'       # Elimina paquetes con APT.
alias sudo-shutdown='sudo shutdown now'       # Apaga el sistema de inmediato.
alias sudo-ifconfig='sudo ifconfig'           # Muestra o configura interfaces de red.
